dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: VJR5s+kPQecs+cww0Kt8AKKwBp+D9NvSbbTGASGSUJ2XhXT4/Q+N2wEHIu97Jl80LxN55cm0lPakyfT9uPkWD5ZXn0nbFPYjsiGhOrspUNPH8TL/RWx01uSk3ortUb1igzdCps88NWRNIM+tfzdYmdjMSbEs0ve7dCW2nvoJT7Zaf+Q83KadQXd2+6ekuwfsBy++KW0rW2szNpFalG8kPC7BX4vZEW5q45EGQ+NuqHQqd21/Mk2Gc69Rd9aWywqAYR7j998YdoaHpk6y4zIdm+ZpOawaIHp7r3qeq2REktphy/dBafJ4QwNeYMvrny/thw/srkyFQVFQK9SBZ8oOMJsRwR/BguqKoFQwftyFo+ZdRt/YGhI5X98dFZIfKLsItNlEaLvWXjq6pwgi+CsfczFJ9nkhikPBm9jeSvK3x7yTkw8leSwhiVlNPzG6iVywZYJfkWXu0mnkwGYtl4iphvwhgUYpXhjqKGZeyOzIEGIhfLCjZqdVSCyDyqKZhVEGG77tQcOZvK2yhm3KxdGWBdaARkZif8REUjCOMFYd67G5InTG8sYaNmif0GQxtA/RvOGWqzZfWcridKQeAHtnxZM0iSGF4cs3cII/4czmixWlzcbyqY589fNJ4ERq7DQ55QprHDVTnsXGwTBHM4t8FDV3kAWOPetzvOrcht2JAh8=
