dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: Ra/4h5aLXBq4aPelpCH8GJZQwYweGN5vbT4HydiNN84i5jOatzZfHPEC0SYY1tFwSvjllZYr4Buzy72qN9BrR2XxQt6kuID+vG8oX+UQezzmitqfp7eiEGay1xWRSSzg4DLFMUkJVT8k0ocLTHXBFzGfDkrj7vlRI79eiruHkwGuM4BGSuz/M3bKS+/RLxrvltDOS/FZYYalxjiYc64264tSokze8VsOpls8tLSE0jd1hGjzQaY9tqQT0sKg8ZdxMmFWU8OFdWYpPKc/szLyhdxQxOR/ipyLydLtYFiMVcNWXm8CMoB0fCT7yybJ3ehoksi0h8MJ4dTLLj4IIZb/4J92NBBseqyESaYOO9/iS2UId+qHFCS9QuQNnxD3dFOZgHcUCJ+e29smTQw0cVxQhaPNRA45MKUZA+pqXJI0xrK0gyoFwRH7lDKpjmfZZr2Jl/fMoeh/uvEt2Q6dDO9tzYbDe65NRjK7NZBKQ4fLCAgrJMJCQ3gOFuCy5KCDWRHUX06IXT00qZK3y2l9r6dYbYkBInF57LkOxZY7E52FYMK1np8KIgiaqgTwE+6PrNls9/7RupGNhVOOPt9nXy/0hQULC+UMIc4ccQub+MhguvtTMNliJJP9hN5LMLF+BKypgE0C6e4VynDiWwtlt1UZ3KpfdvPcNBWpWDBxO2FtJOw=
