dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: S9nmJMmlvAVZKio+vuJiNi5hAF18vTMkQDLSateDfjjGyeOtRm3/VnxFGLGnx2IF8DSUM/d79xXDnmdnyDVf+CxNzRnv+1a8+zWOq7YKiRqvXpxLnJFJOf729BGMaFvH7urdi5TaYI5gqg2rmF7j4PHcFvmnkKKrh/MhlELv7ENlT3e0ghwtIKyJijBexRI8bcMh6nVX4NclA/dVDR22V9ps4yUoIw4RiBQTKkL8FZqpMD3PsTu7tm3ksNfpv6DajkKivS+ueoAZoVAaC1AGy1YazU3oKrti9+PnAJoTC7Lav0eBcYr2E5rqBH3pk61ki7g9u8AhzFivYejpFzsX3Q/tuVWEbSh+AQcHNRxVp+R4+4Y86q+ldFeU1SVsCylc1jFu1yRTm4H020jr+VQE9EqwIABKnd+PldNAWf7sXwyCpA26+zVax3Ymj2cvGZCP73Dq07cJPoFGVitEUWlCKb5c+gl6Zo/fBfjoDHAk8W+D/M4N3qpwkDhJf9qg15+5owAY16kEhD8DMRpP0bfg6wQnDD7N1xsyj+bCUWIzhBMkDpWuPW/9BlD0d5j95neBsS+HDt70nFcOwkX/TDJ98Xw1p6U5kT2kZXVgWUICfgVlIeoHQKNXpsOQHMZx8YnNE8chMs8XnolC2Utbfb+5RyyyHL1V+L/Etf/vk8EZBJQ=
