---
- name: Install apt-transport-https
  apt:
    update_cache: yes
    name:
    - apt-transport-https
  tags: install
- name: Add Mongo repo key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present
  tags: install

- name: Add repo into sources list
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
    state: present
  tags: install

- name: Install MongoDB
  apt:
    update_cache: yes
    name: mongodb-org
  tags: install

- name: Start Mongo
  service:
    name: mongod
    state: started
  tags: install

- name: Enable Mongo
  service:
    name: mongod
    enabled: yes
  tags: install
