- name: Clone
  hosts: app
  tasks:
  - name: Install git
    apt:
      name: git
    become: true
  - name: Clone repo
    git:
      repo: https://github.com/express42/reddit.git
      dest: /home/ubuntu/reddit
