- name: Configure MongoDB
  hosts: db
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify:
      - restart mongodb
  handlers:
  - name: restart mongodb
    service:
      name: mongod
      state: restarted
  tags: db-tag

- name: Configure App
  hosts: app
  become: true
  vars:
    db_host: 10.130.0.8
  tasks:
  - name: Add unit file for Puma
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    notify: reload puma
  - name: Add config for db connection
    template:
      src: files/db_config.j2
      dest: /home/ubuntu/db_config
      owner: ubuntu
      group: ubuntu
  - name: enable puma
    service:
      name: puma
      enabled: yes
  handlers:
  - name: reload puma
    service:
      name: puma
      state: restarted
  tags: app-tag

- name: Deploy App
  hosts: app
  tasks:
  - name: Install git
    apt:
      name: git
    become: true
  - name: Clone repo
    git:
      repo: https://github.com/express42/reddit.git
      dest: /home/ubuntu/reddit
      version: monolith
    notify: reload puma
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit
  handlers:
  - name: reload puma
    become: true
    service:
      name: puma
      state: restarted
  tags: deploy-tag
